In [2]:
import numpy as np
#fill array with zeros
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# fill array with ones
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# fill array with value N
n = np.full(10, 2)
n

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# np.where
a = np.arange(10, 20)
w = np.where(a == 12)
w

(array([2]),)

In [12]:
# index array with another array
b = np.arange(10,100,2)
b[w]

array([14])

In [15]:
# concatenate two arrays
ohs = np.zeros(100)
nums = np.linspace(0,1,100)
np.concatenate([ohs,nums])


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     